/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    let hash = {};

    for (num of s) {
        if (hash[num]) {
            hash[num] += 1;
        } else {
            hash[num] = 1;
        }
    }

    for (let char of t) {
        if (hash[char] && hash[char] > 0) {
            hash[char]--;
        } else {
            return char;
        }
    }
    return -1;
};



// You are given two strings s and t.

// // String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.